---
title: 'Mixtures Workshop: Grouped Lasso'
author: "Lizzy Gibson"
date: "July 18, 2018"
output: 
  html_document:
    toc: TRUE
    toc_float: TRUE
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
#install.packages("tidyverse")
library(tidyverse)
#install.packages("grpreg")
library(grpreg)
#install.packages("splines")
library(splines)
#install.packages("refund")
library(refund)
#install.packages("refund.shiny")
library(refund.shiny)
#install.packages("janitor")
library(janitor)

#This turns off scientific notation
options(scipen = 999)
```

## Data

```{r clean}
studypop <- read_csv("./Data/studypop.csv") %>% clean_names() %>% na.omit() %>% #remove missing
  mutate(bmi_cat3 = as.factor(bmi_cat3),
  edu_cat = as.factor(edu_cat),
  race_cat = as.factor(race_cat),
  male = as.factor(male)) %>% #create factor variables
  dplyr::select(-seqn) #remove ID variable

#Group lasso wants data SEPARATE, with y value as one vector, X as a matrix of predictors (numeric values, categorical variables must be changed to 0/1 dummy variables), and grouping variable as a factor vector.

#Create X matrix of predictors with ln-transformed continuous variables (PCBs, Dioxins, and Furans) and dummy variables for categorical.
x <- model.matrix(telomean ~ ., studypop)[,-1]
#ln transform
x[,1:8] <- log(x[,1:8])
x[,15:24] <- log(x[,15:24])
#grpreg standardizes the data, so we don't need to
#These are complete cases

#y is the outcome variable
#ln transform
y <- log(studypop$telomean)


#Create grouping variable two ways. If there are coefficients to be included in the model without being penalized, assign them to group 0 (or "0"). This includes all covaruiates we want to keep in the model. Group must be a FACTOR. 

# (1) 3 groups = 8 non-Dioxin-like PCBs, 2 non-ortho PCBs, and TEQ (3 dioxins, 4 furans, 1 mono-ortho (Dioxin-like) PCBs). 
group3 <- vector()
group3[grepl("lbx1|0",colnames(x))] <- "Non-Dioxin-like PCB"
group3[grepl("lbxd", colnames(x))] <- "TEQ"
group3[grepl("lbxf", colnames(x))] <- "TEQ"
group3[grepl("lbxh|p", colnames(x))] <- "Non-Ortho PCB"
group3[grepl("lbx118la", colnames(x))] <- "TEQ"
group3[grepl("pct", colnames(x))] <- "0"
group3[grepl("bcsi", colnames(x))] <- "0"
group3[grepl("bmi", colnames(x))] <- "0"
group3[grepl("edu", colnames(x))] <- "0"
group3[grepl("race", colnames(x))] <- "0"
group3[grepl("male", colnames(x))] <- "0"
group3[grepl("bxcot", colnames(x))] <- "0"
group3[grepl("age", colnames(x))] <- "0"
group3 <- as.factor(group3)

cbind(colnames(x), group3)

# (2) 4 groups = 8 non-dioxin-like PCBs, 3 non-ortho PCBs, 3 dioxins, and 4 furans.

group4 <- vector()
group4[grepl("lbx1|0",colnames(x))] <- "Non-Dioxin-like PCB"
group4[grepl("lbxd", colnames(x))] <- "Dioxin"
group4[grepl("lbxf", colnames(x))] <- "Furan"
group4[grepl("lbxh|p", colnames(x))] <- "Non-Ortho PCB"
group4[grepl("lbx118la", colnames(x))] <- "Non-Ortho PCB"
group4[grepl("pct", colnames(x))] <- "0"
group4[grepl("bcsi", colnames(x))] <- "0"
group4[grepl("bmi", colnames(x))] <- "0"
group4[grepl("edu", colnames(x))] <- "0"
group4[grepl("race", colnames(x))] <- "0"
group4[grepl("male", colnames(x))] <- "0"
group4[grepl("bxcot", colnames(x))] <- "0"
group4[grepl("age", colnames(x))] <- "0"
group4 <- as.factor(group4)
cbind(colnames(x), group4)
```

## Grouped Variable Selection

```{r models}
lasso_3 <- grpreg(x, y, group3, penalty = "grLasso")
MCP_3 <- grpreg(x, y, group3, penalty = "grMCP")
SCAD_3 <- grpreg(x, y, group3, penalty = "grSCAD")

par(mfrow = c(1,3))
plot(lasso_3)
plot(MCP_3)
plot(SCAD_3)

lasso_4 <- grpreg(x, y, group4, penalty = "grLasso")
MCP_4 <- grpreg(x, y, group4, penalty = "grMCP")
SCAD_4 <- grpreg(x, y, group4, penalty = "grSCAD")

par(mfrow = c(1,3))
plot(lasso_4)
plot(MCP_4)
plot(SCAD_4)
```

## Lasso w/ CV

```{r cvlasso}
#3 group model

#Cross-validation to choose the best tuning parameter lambda, ten-fold default
cv_lasso_3 <- cv.grpreg(x, y, group3
                        , penalty = "grLasso"
                        , seed = 1988
                        )

best_lasso_3 <- cv_lasso_3$lambda.min
#This is the lambda that results in the smallest cross-validation error

#Fit model with cross-validated lambda
fit_lasso_3 <- grpreg(x, y, group3, penalty = "grLasso"
                      , lambda = best_lasso_3
                      )

#look at coefficients from model with best lambda
fit_lasso_3$beta

#4 group model
#Cross-validation to choose the best tuning parameter lambda, ten-fold default
cv_lasso_4 <- cv.grpreg(x, y, group4, penalty = "grLasso", seed = 1988)

best_lasso_4 <- cv_lasso_4$lambda.min
#This is the lambda that results in the smallest cross-validation error

#Fit model with cross-validated lambda
fit_lasso_4 <- grpreg(x, y, group4, penalty = "grLasso", 
                      lambda = best_lasso_4)

#look at coefficients from model with best lambda
fit_lasso_4$beta
```

### Data Viz

```{r vizlasso}
#3 group model
lasso_beta_3 <- cbind(rownames(fit_lasso_3$beta), fit_lasso_3$beta) %>% as.tibble() %>% 
  rename(variable = V1, beta = `0.0058`) %>% 
  mutate(beta = as.numeric(beta)) %>% filter(variable != "(Intercept)") %>% 
  mutate(group3 = group3,
         group4 = group4,
         method = "Grouped Lasso")

#Filter out covariates
lasso_beta_3 %>% filter(group3 %in% 
                          c("TEQ", "Non-Dioxin-like PCB", "Non-Ortho PCB")) %>% 
  ggplot(aes(x = variable, 
                       y = round(beta, 5))) + geom_point() +
  theme_minimal() + geom_hline(yintercept = 0, color = "red", linetype = "dashed") +
  facet_wrap(~group3, scales = "free_y") +
  theme(axis.text.x = element_text(angle = 90, hjust = 1)) +
  coord_flip() + 
  labs(title = "Lasso Coefficients for 3 Group Model", y = "Beta Coefficient",
       x = "Variable")

#4 group model
lasso_beta_4 <- cbind(rownames(fit_lasso_4$beta), fit_lasso_4$beta) %>% as.tibble() %>% 
  rename(variable = V1, beta = `0.0059`) %>% 
  mutate(beta = as.numeric(beta)) %>% filter(variable != "(Intercept)") %>% 
  mutate(group3 = group3,
         group4 = group4)

#Filter out covariates
lasso_beta_4 %>% 
  filter(group4 %in% c("Dioxin", "Furan", "Non-Dioxin-like PCB", "Non-Ortho PCB")) %>% 
  ggplot(aes(x = variable, 
                       y = round(beta, 5))) + geom_point() +
  theme_minimal() + geom_hline(yintercept = 0, color = "red", linetype = "dashed") +
  facet_wrap(~group4, scales = "free_y") +
  theme(axis.text.x = element_text(angle = 90, hjust = 1)) +
  coord_flip() + 
  labs(title = "Lasso Coefficients for 4 Group Model", y = "Beta Coefficient",
       x = "Variable")
```

## MCP w/ CV

```{r cvmcp}
#3 group model

#Cross-validation to choose the best tuning parameter lambda, ten-fold default
cv_mcp_3 <- cv.grpreg(x, y, group3
                        , penalty = "grMCP"
                        , seed = 1988
                        )

best_mcp_3 <- cv_mcp_3$lambda.min
#This is the lambda that results in the smallest cross-validation error

#Fit model with cross-validated lambda
fit_mcp_3 <- grpreg(x, y, group3, penalty = "grMCP"
                      , lambda = best_mcp_3
                      )

#look at coefficients from model with best lambda
fit_mcp_3$beta

#4 group model
#Cross-validation to choose the best tuning parameter lambda, ten-fold default
cv_mcp_4 <- cv.grpreg(x, y, group4, penalty = "grMCP", seed = 1988)

best_mcp_4 <- cv_mcp_4$lambda.min
#This is the lambda that results in the smallest cross-validation error

#Fit model with cross-validated lambda
fit_mcp_4 <- grpreg(x, y, group4, penalty = "grMCP", 
                      lambda = best_mcp_4)

#look at coefficients from model with best lambda
fit_mcp_4$beta
```

### Data Viz

```{r vizmcp}
#3 group model
mcp_beta_3 <- cbind(rownames(fit_mcp_3$beta), fit_mcp_3$beta) %>% as.tibble() %>% 
  rename(variable = V1, beta = `0.0123`) %>% 
  mutate(beta = as.numeric(beta)) %>% filter(variable != "(Intercept)") %>% 
  mutate(group3 = group3,
         group4 = group4,
         method = "MCP")

#Filter out covariates
mcp_beta_3 %>% filter(group3 %in% 
                          c("TEQ", "Non-Dioxin-like PCB", "Non-Ortho PCB")) %>% 
  ggplot(aes(x = variable, 
                       y = round(beta, 5))) + geom_point() +
  theme_minimal() + geom_hline(yintercept = 0, color = "red", linetype = "dashed") +
  facet_wrap(~group3, scales = "free_y") +
  theme(axis.text.x = element_text(angle = 90, hjust = 1)) +
  coord_flip() + 
  labs(title = "MCP Coefficients for 3 Group Model", y = "Beta Coefficient",
       x = "Variable")

#4 group model
mcp_beta_4 <- cbind(rownames(fit_mcp_4$beta), fit_mcp_4$beta) %>% as.tibble() %>% 
  rename(variable = V1, beta = `0.0085`) %>% 
  mutate(beta = as.numeric(beta)) %>% filter(variable != "(Intercept)") %>% 
  mutate(group3 = group3,
         group4 = group4)

#Filter out covariates
mcp_beta_4 %>% 
  filter(group4 %in% c("Dioxin", "Furan", "Non-Dioxin-like PCB", "Non-Ortho PCB")) %>% 
  ggplot(aes(x = variable, 
                       y = round(beta, 5))) + geom_point() +
  theme_minimal() + geom_hline(yintercept = 0, color = "red", linetype = "dashed") +
  facet_wrap(~group4, scales = "free_y") +
  theme(axis.text.x = element_text(angle = 90, hjust = 1)) +
  coord_flip() + 
  labs(title = "MCP Coefficients for 4 Group Model", y = "Beta Coefficient",
       x = "Variable")
```

## SCAD w/ CV

```{r cvscad}
#3 group model

#Cross-validation to choose the best tuning parameter lambda, ten-fold default
cv_scad_3 <- cv.grpreg(x, y, group3
                        , penalty = "grSCAD"
                        , seed = 1988
                        )

best_scad_3 <- cv_scad_3$lambda.min
#This is the lambda that results in the smallest cross-validation error

#Fit model with cross-validated lambda
fit_scad_3 <- grpreg(x, y, group3, penalty = "grSCAD"
                      , lambda = best_scad_3
                      )

#look at coefficients from model with best lambda
fit_scad_3$beta

#4 group model
#Cross-validation to choose the best tuning parameter lambda, ten-fold default
cv_scad_4 <- cv.grpreg(x, y, group4, penalty = "grSCAD", seed = 1988)

best_scad_4 <- cv_scad_4$lambda.min
#This is the lambda that results in the smallest cross-validation error

#Fit model with cross-validated lambda
fit_scad_4 <- grpreg(x, y, group4, penalty = "grSCAD", 
                      lambda = best_scad_4)

#look at coefficients from model with best lambda
fit_scad_4$beta
```

### Data Viz

```{r vizscad}
#3 group model
scad_beta_3 <- cbind(rownames(fit_scad_3$beta), fit_scad_3$beta) %>% as.tibble() %>% 
  rename(variable = V1, beta = `0.0077`) %>% 
  mutate(beta = as.numeric(beta)) %>% filter(variable != "(Intercept)") %>% 
  mutate(group3 = group3,
         group4 = group4,
         method = "SCAD")

#Filter out covariates
scad_beta_3 %>% filter(group3 %in% 
                          c("TEQ", "Non-Dioxin-like PCB", "Non-Ortho PCB")) %>% 
  ggplot(aes(x = variable, 
                       y = round(beta, 5))) + geom_point() +
  theme_minimal() + geom_hline(yintercept = 0, color = "red", linetype = "dashed") +
  facet_wrap(~group3, scales = "free_y") +
  theme(axis.text.x = element_text(angle = 90, hjust = 1)) +
  coord_flip() + 
  labs(title = "SCAD Coefficients for 3 Group Model", y = "Beta Coefficient",
       x = "Variable")

#4 group model
scad_beta_4 <- cbind(rownames(fit_scad_4$beta), fit_scad_4$beta) %>% as.tibble() %>% 
  rename(variable = V1, beta = `0.0071`) %>% 
  mutate(beta = as.numeric(beta)) %>% filter(variable != "(Intercept)") %>% 
  mutate(group3 = group3,
         group4 = group4)

#Filter out covariates
scad_beta_4 %>% 
  filter(group4 %in% c("Dioxin", "Furan", "Non-Dioxin-like PCB", "Non-Ortho PCB")) %>% 
  ggplot(aes(x = variable, 
                       y = round(beta, 5))) + geom_point() +
  theme_minimal() + geom_hline(yintercept = 0, color = "red", linetype = "dashed") +
  facet_wrap(~group4, scales = "free_y") +
  theme(axis.text.x = element_text(angle = 90, hjust = 1)) +
  coord_flip() + 
  labs(title = "SCAD Coefficients for 4 Group Model", y = "Beta Coefficient",
       x = "Variable")
```

```{r create_4_plot}
grouped <- rbind(lasso_beta_3, mcp_beta_3, scad_beta_3) %>% 
  dplyr::select(-group3, -group4)

write_csv(grouped, "grouped_betas.csv")
```

