---
title: "Principal Component Analysis"
author: "Yanelli Nunez"
date: "8/13/2018"
output: 
  html_document:
    toc: TRUE
    toc_float: TRUE
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
#install.packages("tidyverse")
library(tidyverse)
#install.packages("janitor")
library(janitor)
#install.packages("ggplot2")
library(ggplot2)
#install.packages("ggcorrplot")
library(ggcorrplot)
#install.packages("ggfortify")
library(ggfortify)  
#install.packages("gridExtra")
library(gridExtra)
#install.packages("factoextra")
library(factoextra)

```

# Data Import and Cleaning

```{r data preping}
studypop <- read_csv("./Data/studypop.csv") %>% 
  clean_names() %>% 
  mutate(bmi_cat3 = as.factor(bmi_cat3),
  edu_cat = as.factor(edu_cat),
  race_cat = as.factor(race_cat),
  male = as.factor(male))

#check dimensions of dataset
dim(studypop)

#summary statistics on dataset
summary(studypop)

#extract Non-dioxin-like PCB variables from the studypop data frame
my.x <- names(studypop)[grep("la", names(studypop))] 

#create a new data frame with my.x and convert values for the predictor variables to its natural log.
log.x <- data.frame(apply(studypop[,my.x], 2, FUN = function(x) log(x))) %>%
  setNames(paste(my.x, "l2", sep = ".")) %>% #add suffix 12 to the predictors' name
  na.omit() #remove missing

#check dimensions of dataset
dim(log.x)

#summary statistics on dataset
summary(log.x)
```

# Principal Component Analysis (PCA)

## PCA using Log-Transformed Data

```{r PCA in log data}
#PCA
pca.ln  <- prcomp(log.x, scale = TRUE) #scale: a logical value indicating whether the variables should be scaled to have unit variance before the analysis takes place
summary(pca.ln)

eigen_log = pca.ln$sdev^2 #eigenvalues

#Proportion of variance explained by each component
pve.ln <- pca.ln$sdev^2/sum(pca.ln$sdev^2)
```

## PCA using Raw Data

```{r PCA in raw data}
#PCA
pca.raw <- prcomp(na.omit(studypop[my.x]), scale = TRUE) 
summary(pca.raw)

eigen_raw = pca.raw$sdev^2 #eigenvalues

#Proportion of variance explained by each component
pve.raw <- pca.raw$sdev^2/sum(pca.raw$sdev^2)
```

## Proportion of Variance Plots

```{r PVE plots}
par(mfrow = c(1,2))
#Plots the proportion of variance explained by each component 

#log-transformed data
fviz_eig(pca.ln, main = "Log - Transformed data",
         xlab = "Principal component",
         ylim = c(0,70)) 

#Raw data
fviz_eig(pca.raw, main = "Raw data",
         xlab = "Principal component",
         ylim = c(0,70))

```


## Data Visualization of eigenvectors w/ Log-Transformed PCA Results

```{r PCA loadings}
#create a data frame of the loadings
pca.ln.ld <- as.data.frame.matrix(pca.ln$rotation)
pca.ln.ld$chem <- row.names(pca.ln.ld)

#Bars represent eigenvectors
c1plot <- ggplot(pca.ln.ld, aes(x = chem, y = PC1)) + geom_bar(stat = "identity") +
  theme_bw() +  xlab("Chemicals") + ylab("Component 1")  + 
  theme(axis.title.x = element_blank(), axis.text.x = element_blank()) + 
  ylim(min(pca.ln.ld[,1:4]), max(pca.ln.ld[,1:4]))

c2plot <- ggplot(pca.ln.ld, aes(x = chem, y = PC2)) + geom_bar(stat = "identity") +
  theme_bw() + xlab("Chemicals") + ylab("Component 2")  + 
  theme(axis.title.x = element_blank(), axis.text.x = element_blank()) + 
  ylim(min(pca.ln.ld[,1:4]), max(pca.ln.ld[,1:4]))

c3plot <- ggplot(pca.ln.ld, aes(x = chem, y = PC3)) + geom_bar(stat = "identity") +
  theme_bw() + xlab("Chemicals") + ylab("Component 3")  + 
  theme(axis.text.x = element_text(angle = 90, hjust = 1)) + 
  ylim(min(pca.ln.ld[,1:4]), max(pca.ln.ld[,1:4]))

c4plot <- ggplot(pca.ln.ld, aes(x = chem, y = PC4)) + geom_bar(stat = "identity") +
  theme_bw() + xlab("Chemicals") + ylab("Component 4")  + 
  theme(axis.text.x = element_text(angle = 90, hjust = 1)) + 
  ylim(min(pca.ln.ld[,1:4]), max(pca.ln.ld[,1:4]))

grid.arrange(c1plot, c2plot, c3plot, c4plot, ncol = 2)
```

## Principal Component Biplot w/ Log-Transformed PCA Results

```{r PCA biplot}
#Creates a biplot showing the loadings for principal component 1 and 2. 
autoplot(pca.ln, data = log.x, size = 0.8, colour = 'blue', alpha = 0.5,
         loadings = TRUE, loadings.colour = 'orange',
         loadings.label = TRUE, loadings.label.repel = T, 
         loadings.label.size = 2.5, loadings.label.colour = 'black',
         main = "Principal Component Analysis Biplot")
```



