---
title: "Variable Selection Visualization"
author: "Lizzy Gibson"
date: "7/26/2018"
output: 
  html_document:
    toc: TRUE
    toc_float: TRUE
---

```{r setup, include=FALSE}
library(tidyverse)
#install.packages("tidyverse")
```

## Combine Effect Estimates

```{r}
grouped <- read_csv("./grouped_betas.csv")
ind <- read_csv("./ind_betas.csv")

plot_all <- rbind(grouped, ind) %>% filter(grepl("la$", variable)) 
```

## Compare Variable Selection Methods

```{r}
plot_all %>%
  ggplot(aes(x = variable, y = round(beta, 5))) + 
  geom_point(aes(color = method)) +
  theme_minimal() + geom_hline(yintercept = 0, color = "red", linetype = "dashed") +
  theme(axis.text.x = element_text(angle = 90, hjust = 1), legend.position = "bottom") + 
  coord_flip() + 
  labs(title = "Variable Selection Coefficients", 
       y = "Beta Coefficients", 
       x = "Variable", 
       color = "Method")
```

```{r}
plot_all %>%
  ggplot(aes(x = method, y = round(beta, 5))) + geom_point(aes(color = method)) +
  theme_minimal() + geom_hline(yintercept = 0, color = "red", linetype = "dashed") +
  theme(axis.text.x = element_text(angle = 90, hjust = 1), legend.position = "none") +
  facet_wrap( ~ variable) + coord_flip() + 
  labs(title = "Variable Selection Coefficients", 
       y = "Beta Coefficients",
       x = "Variable", 
       color = "Method")
```
