---
title: "Weighted Quantile Sum Regression"
author: "Chris Gennings and Stefano Renzetti"
date: "8/16/2018"
output: 
  html_document:
    toc: TRUE
    toc_float: TRUE
    toc_depth : 4
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
#install.packages("gWQS", dependencies = TRUE)
#devtools::package_deps("gWQS") can use this to see which package dependencies you already have
library(gWQS)
library(tidyverse)
```

## Data Import and Cleaning

```{r import}
# import the dataset
dataset = read_csv("./Data/studypop.csv")

# define the chemicals to include in the mixture
mixture = c("LBX074LA", "LBX099LA", "LBX118LA", "LBX138LA", "LBX153LA", "LBX170LA", "LBX180LA", "LBX187LA",
            "LBX194LA", "LBXD03LA", "LBXD05LA", "LBXD07LA", "LBXF03LA", "LBXF04LA", "LBXF05LA", "LBXF08LA",
            "LBXHXCLA", "LBXPCBLA")

```

## Weighted Quantile Sums

### Unadjusted Model

```{r model_1}
# fit a first unadjusted model to look at the association between the mixture and the outcome
# TELOMEAN = Mean Telomere Length
results1 = gwqs(log(TELOMEAN) ~ NULL, mix_name = mixture, data = dataset, q = 10, validation = 0.6, 
                valid_var = NULL,b = 100, b1_pos = FALSE, b1_constr = TRUE, family = "gaussian", 
                seed = 100597, wqs2 = FALSE, plots = TRUE, tables = TRUE)

summary(results1$fit)
results1$final_weights %>% knitr::kable()
```

### Adjusted Model

```{r model_2}
# adjust for covariates:
# blood data: LBXWBCSI LBXLYPCT LBXMOPCT LBXEOPCT LBXBAPCT LBXNEPCT
# demographics: age_cent age_sq race_cat bmi_cat3 ln_lbxcot edu_cat

# redefine variables race_cat and edu_cat as factors
dataset$race_cat = factor(dataset$race_cat, levels = c(1, 2, 3, 4), labels = c(1, 2, 3, 4))
dataset$edu_cat = factor(dataset$edu_cat, levels = c(1, 2, 3, 4), labels = c(1, 2, 3, 4))
dataset$bmi_cat3 = factor(dataset$bmi_cat3, levels = c(1, 2, 3), labels = c(1, 2, 3))

result2 = gwqs(log(TELOMEAN) ~ LBXWBCSI + LBXLYPCT + LBXMOPCT + LBXEOPCT + LBXBAPCT + LBXNEPCT + age_cent +
                 age_sq + race_cat + bmi_cat3 + ln_lbxcot + edu_cat + male, mix_name = mixture, 
                 data = dataset, q = 10, 
                 validation = 0.6, valid_var = NULL, b = 100, b1_pos = TRUE, b1_constr = TRUE, 
                 family = "gaussian", seed = 100597, wqs2 = FALSE, plots = TRUE, tables = TRUE)

summary(result2$fit)

result2$final_weights %>% knitr::kable()
```

### Constrained Model

```{r model_3}
# adjusting for covariates and constraining direction to negative:
# blood data: LBXWBCSI LBXLYPCT LBXMOPCT LBXEOPCT LBXBAPCT LBXNEPCT
# demographics: age_cent age_sq race_cat bmi_cat3 ln_lbxcot edu_cat
result3 = gwqs(log(TELOMEAN) ~ LBXWBCSI + LBXLYPCT + LBXMOPCT + LBXEOPCT + LBXBAPCT + LBXNEPCT + 
               age_cent + age_sq + race_cat + bmi_cat3 + ln_lbxcot + edu_cat, 
               mix_name = mixture, data = dataset, q = 10, 
               validation = 0.6, valid_var = NULL, b = 100, b1_pos = FALSE, 
               b1_constr = TRUE, family = "gaussian", 
               seed = 123, wqs2 = FALSE, plots = TRUE, tables = TRUE)

summary(result3$fit)

result3$final_weights %>% knitr::kable()
```

### Stratified Model

```{r model_4}
# stratified analysis by sex
# create diagonal matrices for females and male having on the diagonal 1 or 0 to select female or males values respectively
M_mat = diag(dataset$male)
female = (dataset$male - 1)*(-1)
F_mat = diag(female)
# create the matrix containing the mixture variables
X = as.matrix(dataset[, mixture])
# create a temporary matrix where we substitute NAs with 0s before the matrix multiplication
X_t = X
X_t[is.na(X)] = 0
# create a matrix for females and males selecting the observations that corresponds to each sex
XM = M_mat%*%X_t
XF = F_mat%*%X_t
# put back the NAs in the same position they were in the X matrix
XM[is.na(X)] = NA
XF[is.na(X)] = NA
# create the vectors containing the names of the chemicals for males and females
mixture_m = paste(mixture, "m", sep = "_")
mixture_f = paste(mixture, "f", sep = "_")
# rename the columns of the females and males matrices
colnames(XM) = mixture_m
colnames(XF) = mixture_f
# add the new variables to the dataset
dataset_new = cbind(dataset, XM, XF)

# run the wqs model using the stratified variables in the mixtures
mixture_new = c(mixture_m, mixture_f)
result4 = gwqs(log(TELOMEAN) ~ LBXWBCSI + LBXLYPCT + LBXMOPCT + LBXEOPCT + LBXBAPCT + LBXNEPCT + 
               age_cent + age_sq + race_cat + bmi_cat3 + ln_lbxcot + edu_cat, 
               mix_name = mixture_new, data = dataset_new, q = 10, 
               validation = 0.6, valid_var = NULL, b = 100, b1_pos = TRUE, b1_constr = FALSE, 
               family = "gaussian", seed = 123, wqs2 = FALSE, plots = TRUE, tables = TRUE)

summary(result4$fit)

result4$final_weights %>% knitr::kable()

```

